import * as DBus from 'dbus-final';
import { interface as DbusInterface } from 'dbus-final';
import { EventEmitter } from 'events';
import { VariantLike, VariantObject } from '../../types';
import { TimeDate1Properties } from './timedate1.types';

/*
 * Generated by dbus-final interface generator
 * Template: typescript-class.ts.hbs
 */

// Introspection XML of org.freedesktop.timedate1 at /org/freedesktop/timedate1
const XMLObjectData = `<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
 <interface name='org.freedesktop.DBus.Peer'>
  <method name='Ping'/>
  <method name='GetMachineId'>
   <arg type='s' name='machine_uuid' direction='out'/>
  </method>
 </interface>
 <interface name='org.freedesktop.DBus.Introspectable'>
  <method name='Introspect'>
   <arg name='data' type='s' direction='out'/>
  </method>
 </interface>
 <interface name='org.freedesktop.DBus.Properties'>
  <method name='Get'>
   <arg name='interface' direction='in' type='s'/>
   <arg name='property' direction='in' type='s'/>
   <arg name='value' direction='out' type='v'/>
  </method>
  <method name='GetAll'>
   <arg name='interface' direction='in' type='s'/>
   <arg name='properties' direction='out' type='a{sv}'/>
  </method>
  <method name='Set'>
   <arg name='interface' direction='in' type='s'/>
   <arg name='property' direction='in' type='s'/>
   <arg name='value' direction='in' type='v'/>
  </method>
  <signal name='PropertiesChanged'>
   <arg type='s' name='interface'/>
   <arg type='a{sv}' name='changed_properties'/>
   <arg type='as' name='invalidated_properties'/>
  </signal>
 </interface>
 <interface name='org.freedesktop.timedate1'>
  <property name='Timezone' type='s' access='read'>
  </property>
  <property name='LocalRTC' type='b' access='read'>
  </property>
  <property name='CanNTP' type='b' access='read'>
   <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='false'/>
  </property>
  <property name='NTP' type='b' access='read'>
  </property>
  <property name='NTPSynchronized' type='b' access='read'>
   <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='false'/>
  </property>
  <property name='TimeUSec' type='t' access='read'>
   <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='false'/>
  </property>
  <property name='RTCTimeUSec' type='t' access='read'>
   <annotation name='org.freedesktop.DBus.Property.EmitsChangedSignal' value='false'/>
  </property>
  <method name='SetTime'>
   <arg type='x' name='usec_utc' direction='in'/>
   <arg type='b' name='relative' direction='in'/>
   <arg type='b' name='interactive' direction='in'/>
  </method>
  <method name='SetTimezone'>
   <arg type='s' name='timezone' direction='in'/>
   <arg type='b' name='interactive' direction='in'/>
  </method>
  <method name='SetLocalRTC'>
   <arg type='b' name='local_rtc' direction='in'/>
   <arg type='b' name='fix_system' direction='in'/>
   <arg type='b' name='interactive' direction='in'/>
  </method>
  <method name='SetNTP'>
   <arg type='b' name='use_ntp' direction='in'/>
   <arg type='b' name='interactive' direction='in'/>
  </method>
  <method name='ListTimezones'>
   <arg type='as' name='timezones' direction='out'/>
  </method>
 </interface>
</node>
`;

/**
 * Service: org.freedesktop.timedate1
 * ObjectPath: /org/freedesktop/timedate1
 * Interface: org.freedesktop.timedate1
 * {@see https://www.freedesktop.org/software/systemd/man/org.freedesktop.timedate1.html}
 */
export class TimeDate1Proxy<TProperties = TimeDate1Properties> extends EventEmitter {
  public static Connect(
    bus: DBus.MessageBus,
    objectPath = '/org/freedesktop/timedate1',
    xml: string = XMLObjectData,
  ): Promise<TimeDate1Proxy> {
    return bus.getProxyObject('org.freedesktop.timedate1', objectPath, xml).then((obj) => new TimeDate1Proxy(obj));
  }

  public readonly dbusInterfaceName = 'org.freedesktop.timedate1';
  public dbusObject: DBus.ProxyObject;
  public propertiesDBusInterface: DBus.ClientInterface;
  public thisDBusInterface: DBus.ClientInterface;

  constructor(dbusObject: DBus.ProxyObject) {
    super();
    this.dbusObject = dbusObject;
    this.thisDBusInterface = this.dbusObject.getInterface('org.freedesktop.timedate1');
    this.propertiesDBusInterface = this.dbusObject.getInterface('org.freedesktop.DBus.Properties');

    // forward property change events
    const forwardPropertyChange = (iface: string, changed: any, invalidated: any) => {
      if (iface === this.dbusInterfaceName) {
        this.emit('PropertiesChanged', iface, changed, invalidated);
      }
    };

    // forward all signals
    this.on('newListener', (event: string, listener: (...args: any[]) => void) => {
      if (event === 'PropertiesChanged' && this.listenerCount('PropertiesChanged') === 0) {
        this.propertiesDBusInterface.on('PropertiesChanged', forwardPropertyChange);
      } else {
        this.thisDBusInterface.on(event, listener);
      }
    });
    this.on('removeListener', (event: string, listener: (...args: any[]) => void) => {
      if (event === 'PropertiesChanged' && this.listenerCount('PropertiesChanged') === 0) {
        this.propertiesDBusInterface.removeListener('PropertiesChanged', forwardPropertyChange);
      } else {
        this.thisDBusInterface.removeListener(event, listener);
      }
    });
  }

  /***** Properties *****/

  //TODO: Extract to base class
  public getProperties(): Promise<VariantObject<TProperties>> {
    return this.propertiesDBusInterface.GetAll(this.dbusInterfaceName);
  }

  public getProperty<TKey extends keyof TProperties>(name: TKey): Promise<VariantLike<TProperties[TKey]>> {
    return this.propertiesDBusInterface.Get(this.dbusInterfaceName, name);
  }

  public setProperty<TKey extends keyof TProperties>(name: TKey, value: VariantLike<TProperties[TKey]>): Promise<void> {
    return this.propertiesDBusInterface.Set(this.dbusInterfaceName, name, value);
  }

  @DbusInterface.property({ name: 'Timezone', signature: 's', access: DbusInterface.ACCESS_READ })
  public Timezone(): Promise<string> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'Timezone')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'LocalRTC', signature: 'b', access: DbusInterface.ACCESS_READ })
  public LocalRTC(): Promise<boolean> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'LocalRTC')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'CanNTP', signature: 'b', access: DbusInterface.ACCESS_READ })
  public CanNTP(): Promise<boolean> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'CanNTP')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'NTP', signature: 'b', access: DbusInterface.ACCESS_READ })
  public NTP(): Promise<boolean> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'NTP')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'NTPSynchronized', signature: 'b', access: DbusInterface.ACCESS_READ })
  public NTPSynchronized(): Promise<boolean> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'NTPSynchronized')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'TimeUSec', signature: 't', access: DbusInterface.ACCESS_READ })
  public TimeUSec(): Promise<bigint> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'TimeUSec')
      .then((variant: DBus.Variant) => variant.value);
  }

  @DbusInterface.property({ name: 'RTCTimeUSec', signature: 't', access: DbusInterface.ACCESS_READ })
  public RTCTimeUSec(): Promise<bigint> {
    return this.propertiesDBusInterface
      .Get(this.dbusInterfaceName, 'RTCTimeUSec')
      .then((variant: DBus.Variant) => variant.value);
  }

  /***** Methods *****/

  @DbusInterface.method({ name: 'SetTime', inSignature: 'xbb', outSignature: '' })
  public SetTime(usec_utc: bigint, relative: boolean, interactive = false): Promise<void> {
    return this.thisDBusInterface.SetTime(usec_utc, relative, interactive);
  }

  @DbusInterface.method({ name: 'SetTimezone', inSignature: 'sb', outSignature: '' })
  public SetTimezone(timezone: string, interactive = false): Promise<void> {
    return this.thisDBusInterface.SetTimezone(timezone, interactive);
  }

  @DbusInterface.method({ name: 'SetLocalRTC', inSignature: 'bbb', outSignature: '' })
  public SetLocalRTC(local_rtc: boolean, fix_system: boolean, interactive = false): Promise<void> {
    return this.thisDBusInterface.SetLocalRTC(local_rtc, fix_system, interactive);
  }

  @DbusInterface.method({ name: 'SetNTP', inSignature: 'bb', outSignature: '' })
  public SetNTP(use_ntp: boolean, interactive = false): Promise<void> {
    return this.thisDBusInterface.SetNTP(use_ntp, interactive);
  }

  @DbusInterface.method({ name: 'ListTimezones', inSignature: '', outSignature: 'as' })
  public ListTimezones(): Promise<Array<string>> {
    return this.thisDBusInterface.ListTimezones();
  }
}
