import * as DBus from 'dbus-final';
import { interface as DbusInterface } from 'dbus-final';
import { EventEmitter } from 'events';
import { SettingsConnectionProperties } from './types';
import { VariantLike, VariantObject, VariantParentObject } from '../../types';
import { ConnectionSettings } from './types/ip.settings.types';

/*
 * Generated by dbus-final interface generator
 * Template: typescript-class.ts.hbs
 */

// Introspection XML of org.freedesktop.NetworkManager at /org/freedesktop/NetworkManager/Settings/5
const XMLObjectData = `<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
                      "http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<!-- GDBus 2.74.6 -->
<node>
  <interface name='org.freedesktop.DBus.Properties'>
    <method name='Get'>
      <arg type='s' name='interface_name' direction='in'/>
      <arg type='s' name='property_name' direction='in'/>
      <arg type='v' name='value' direction='out'/>
    </method>
    <method name='GetAll'>
      <arg type='s' name='interface_name' direction='in'/>
      <arg type='a{sv}' name='properties' direction='out'/>
    </method>
    <method name='Set'>
      <arg type='s' name='interface_name' direction='in'/>
      <arg type='s' name='property_name' direction='in'/>
      <arg type='v' name='value' direction='in'/>
    </method>
    <signal name='PropertiesChanged'>
      <arg type='s' name='interface_name'/>
      <arg type='a{sv}' name='changed_properties'/>
      <arg type='as' name='invalidated_properties'/>
    </signal>
  </interface>
  <interface name='org.freedesktop.DBus.Introspectable'>
    <method name='Introspect'>
      <arg type='s' name='xml_data' direction='out'/>
    </method>
  </interface>
  <interface name='org.freedesktop.DBus.Peer'>
    <method name='Ping'/>
    <method name='GetMachineId'>
      <arg type='s' name='machine_uuid' direction='out'/>
    </method>
  </interface>
  <interface name='org.freedesktop.NetworkManager.Settings.Connection'>
    <method name='Update'>
      <arg type='a{sa{sv}}' name='properties' direction='in'/>
    </method>
    <method name='UpdateUnsaved'>
      <arg type='a{sa{sv}}' name='properties' direction='in'/>
    </method>
    <method name='Delete'/>
    <method name='GetSettings'>
      <arg type='a{sa{sv}}' name='settings' direction='out'/>
    </method>
    <method name='GetSecrets'>
      <arg type='s' name='setting_name' direction='in'/>
      <arg type='a{sa{sv}}' name='secrets' direction='out'/>
    </method>
    <method name='ClearSecrets'/>
    <method name='Save'/>
    <method name='Update2'>
      <arg type='a{sa{sv}}' name='settings' direction='in'/>
      <arg type='u' name='flags' direction='in'/>
      <arg type='a{sv}' name='args' direction='in'/>
      <arg type='a{sv}' name='result' direction='out'/>
    </method>
    <signal name='Updated'/>
    <signal name='Removed'/>
    <property type='b' name='Unsaved' access='read'/>
    <property type='u' name='Flags' access='read'/>
    <property type='s' name='Filename' access='read'/>
  </interface>
</node>
`;

/**
 * Service: org.freedesktop.NetworkManager
 * ObjectPath: /org/freedesktop/NetworkManager/Settings/5
 * Interface: org.freedesktop.NetworkManager.Settings.Connection
 *  {@see https://networkmanager.dev/docs/api/latest/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html}
 */
export class SettingsConnectionProxy<TProperties = SettingsConnectionProperties> extends EventEmitter {
  public static Connect(
    bus: DBus.MessageBus,
    objectPath: string,
    xml: string = XMLObjectData,
  ): Promise<SettingsConnectionProxy> {
    return bus
      .getProxyObject('org.freedesktop.NetworkManager', objectPath, xml)
      .then((obj) => new SettingsConnectionProxy(obj));
  }

  public readonly dbusInterfaceName = 'org.freedesktop.NetworkManager.Settings.Connection';
  public dbusObject: DBus.ProxyObject;
  public propertiesDBusInterface: DBus.ClientInterface;
  public thisDBusInterface: DBus.ClientInterface;

  constructor(dbusObject: DBus.ProxyObject) {
    super();
    this.dbusObject = dbusObject;
    this.thisDBusInterface = this.dbusObject.getInterface('org.freedesktop.NetworkManager.Settings.Connection');
    this.propertiesDBusInterface = this.dbusObject.getInterface('org.freedesktop.DBus.Properties');

    // forward property change events
    const forwardPropertyChange = (iface: string, changed: any, invalidated: any) => {
      if (iface === this.dbusInterfaceName) {
        this.emit('PropertiesChanged', iface, changed, invalidated);
      }
    };

    // forward all signals
    this.on('newListener', (event: string, listener: (...args: any[]) => void) => {
      if (event === 'PropertiesChanged' && this.listenerCount('PropertiesChanged') === 0) {
        this.propertiesDBusInterface.on('PropertiesChanged', forwardPropertyChange);
      } else {
        this.thisDBusInterface.on(event, listener);
      }
    });
    this.on('removeListener', (event: string, listener: (...args: any[]) => void) => {
      if (event === 'PropertiesChanged' && this.listenerCount('PropertiesChanged') === 0) {
        this.propertiesDBusInterface.removeListener('PropertiesChanged', forwardPropertyChange);
      } else {
        this.thisDBusInterface.removeListener(event, listener);
      }
    });
  }

  /***** Properties *****/

  public getProperties(): Promise<VariantObject<TProperties>> {
    return this.propertiesDBusInterface.GetAll(this.dbusInterfaceName);
  }

  public getProperty<TKey extends keyof TProperties>(name: TKey): Promise<VariantLike<TProperties[TKey]>> {
    return this.propertiesDBusInterface.Get(this.dbusInterfaceName, name);
  }

  public setProperty<TKey extends keyof TProperties>(name: TKey, value: VariantLike<TProperties[TKey]>): Promise<void> {
    return this.propertiesDBusInterface.Set(this.dbusInterfaceName, name, value);
  }

  @DbusInterface.property({ name: 'Unsaved', signature: 'b', access: DbusInterface.ACCESS_READ })
  public Unsaved(): Promise<boolean> {
    return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Unsaved');
  }

  @DbusInterface.property({ name: 'Flags', signature: 'u', access: DbusInterface.ACCESS_READ })
  public Flags(): Promise<number> {
    return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Flags');
  }

  @DbusInterface.property({ name: 'Filename', signature: 's', access: DbusInterface.ACCESS_READ })
  public Filename(): Promise<string> {
    return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Filename');
  }

  /***** Methods *****/

  @DbusInterface.method({ name: 'Update', inSignature: 'a{sa{sv}}', outSignature: '' })
  public Update(properties: /* a{sa{sv}} */ VariantParentObject<ConnectionSettings>): Promise<void> {
    return this.thisDBusInterface.Update(properties);
  }

  @DbusInterface.method({ name: 'UpdateUnsaved', inSignature: 'a{sa{sv}}', outSignature: '' })
  public UpdateUnsaved(properties: /* a{sa{sv}} */ VariantParentObject<ConnectionSettings>): Promise<void> {
    return this.thisDBusInterface.UpdateUnsaved(properties);
  }

  @DbusInterface.method({ name: 'Delete', inSignature: '', outSignature: '' })
  public Delete(): Promise<void> {
    return this.thisDBusInterface.Delete();
  }

  @DbusInterface.method({ name: 'GetSettings', inSignature: '', outSignature: 'a{sa{sv}}' })
  public GetSettings(): Promise</* a{sa{sv}} */ VariantParentObject<ConnectionSettings>> {
    return this.thisDBusInterface.GetSettings();
  }

  @DbusInterface.method({ name: 'GetSecrets', inSignature: 's', outSignature: 'a{sa{sv}}' })
  public GetSecrets(setting_name: string): Promise</* a{sa{sv}} */ { [key: string]: any }> {
    return this.thisDBusInterface.GetSecrets(setting_name);
  }

  @DbusInterface.method({ name: 'ClearSecrets', inSignature: '', outSignature: '' })
  public ClearSecrets(): Promise<void> {
    return this.thisDBusInterface.ClearSecrets();
  }

  @DbusInterface.method({ name: 'Save', inSignature: '', outSignature: '' })
  public Save(): Promise<void> {
    return this.thisDBusInterface.Save();
  }

  @DbusInterface.method({ name: 'Update2', inSignature: 'a{sa{sv}}ua{sv}', outSignature: 'a{sv}' })
  public Update2(
    settings: /* a{sa{sv}} */ VariantObject<ConnectionSettings>,
    flags: number,
    args: { [key: string]: DBus.Variant },
  ): Promise<{ [key: string]: DBus.Variant }> {
    return this.thisDBusInterface.Update2(settings, flags, args);
  }
}
