import { BadRequestException, Injectable, Logger } from '@nestjs/common';
import { readFile, writeFile } from 'node:fs/promises';
import { Systemd1Service } from '../../dbus/interfaces/systemd1/systemd1.service';
import { TimeDate1Service } from '../../dbus/interfaces/timedate1/timedate1.service';
import { DateTimeInfoDto, DateTimeSettingsDto, NtpSettingsDto } from './dto/date-time.dto';

export const DEFAULT_TIME_SERVER_POOL = ['0.pool.ntp.org', '1.pool.ntp.org', '2.pool.ntp.org', '3.pool.ntp.org'];

// TODO: Empty config file with correct permission should be created during installation
const TIMESYNCD_CONFIG = {
  TEMPLATE: (ntpAddress: string) =>
    `
# This file  is generated by rpi-nest-api. Do not modify manually!
[Time]
NTP=${ntpAddress}
FallbackNTP=${DEFAULT_TIME_SERVER_POOL.join(' ')}
  `,
  GET_REGEXP: /^NTP=(.*)$/m,
};

@Injectable()
export class DateTimeService {
  private readonly logger = new Logger(DateTimeService.name);

  constructor(private timeDate1Service: TimeDate1Service, private systemd1Service: Systemd1Service) {}

  /**
   * Get all timezones available on the system
   */
  public async getAvailableTimezones(): Promise<Array<string>> {
    return await this.timeDate1Service.getAllTimezones();
  }

  /**
   * Get the current date and time settings from the system
   */
  public async getDateTime(): Promise<DateTimeInfoDto> {
    const dateTimeInfo = await this.timeDate1Service.getDateTimeInfo();
    const ntpServer = await this.getNtpAddressFromConfig();

    return {
      ...dateTimeInfo,
      date: dateTimeInfo.date.toISOString(),
      ntpServer,
    };
  }

  /**
   * Set the provided date time settings on the system
   */
  public async setDateTime(dateTime: DateTimeSettingsDto): Promise<void> {
    const currentSettings = await this.timeDate1Service.getDateTimeInfo();
    if (currentSettings.isNtpEnabled) {
      throw new BadRequestException('Cannot set system time while NTP synchronization is enabled');
    }

    this.logger.log(`Setting system time to: ${dateTime.date}`);
    await this.timeDate1Service.setSystemDate(new Date(dateTime.date));

    this.logger.log('Setting TimeZone to: ', dateTime.timeZone);
    await this.timeDate1Service.setTimezone(dateTime.timeZone);
  }

  public async setNtp(ntpSettings: NtpSettingsDto): Promise<void> {
    if (ntpSettings.ntpServer) {
      await this.writeNtpAddressToConfig(ntpSettings.ntpServer);
      // TODO: Move service names to constants
      await this.systemd1Service.RestartUnit('systemd-timesyncd.service');
    }

    await this.timeDate1Service.enableNTP(ntpSettings.isNtpEnabled);
    this.logger.log(`NTP service ${ntpSettings.isNtpEnabled ? 'enabled' : 'disabled'}`);
  }

  /**
   * Read the timesyncd.conf and return the time server address.
   */
  public async getNtpAddressFromConfig(): Promise<string | undefined> {
    try {
      const configPath = this.timeDate1Service.configFilePath;
      const ntpConfig = await readFile(configPath, { encoding: 'utf8' });
      const timeServerAddressMatch = ntpConfig.match(TIMESYNCD_CONFIG.GET_REGEXP);

      if (timeServerAddressMatch === null) {
        this.logger.log('No NTP address set in timesyncd configuration');
        return;
      }

      return timeServerAddressMatch[1];
    } catch (error) {
      this.logger.error('Unable to read timesyncd configuration', error);
    }
  }

  /**
   * Write the time server address to the timesyncd.conf if necessary.
   */
  private async writeNtpAddressToConfig(timeServerAddress: string): Promise<void> {
    const configPath = this.timeDate1Service.configFilePath;
    this.logger.log(`Writing custom NTP ${timeServerAddress} server to file ${configPath}`);

    const timesyncdConfig = TIMESYNCD_CONFIG.TEMPLATE(timeServerAddress);

    await writeFile(configPath, timesyncdConfig, { encoding: 'utf8' });
  }
}
