export const networkDevicesMock: any[] = [
  {
    Udi: '/sys/devices/virtual/net/lo',
    Path: '',
    Interface: 'lo',
    IpInterface: 'lo',
    Driver: 'unknown',
    DriverVersion: '',
    FirmwareVersion: '',
    Capabilities: 5,
    Ip4Address: 0,
    State: 100,
    StateReason: [100, 0],
    ActiveConnection: {
      Connection: '/org/freedesktop/NetworkManager/Settings/6',
      SpecificObject: '/',
      Id: 'lo',
      Uuid: '91b8e863-7794-41fa-9e7d-87b4518dd40c',
      Type: 'loopback',
      Devices: ['/org/freedesktop/NetworkManager/Devices/1'],
      State: 2,
      StateFlags: 220,
      Default: false,
      Ip4Config: '/org/freedesktop/NetworkManager/IP4Config/1',
      Dhcp4Config: '/',
      Default6: false,
      Ip6Config: '/org/freedesktop/NetworkManager/IP6Config/1',
      Dhcp6Config: '/',
      Vpn: false,
      Controller: '/',
      Master: '/',
    },
    Ip4Config: {
      Addresses: [[16777343, 8, 0]],
      AddressData: [
        {
          address: '127.0.0.1',
          prefix: 8,
        },
      ],
      Gateway: '',
      Routes: [],
      RouteData: [],
      NameserverData: [],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
      WinsServerData: [],
      WinsServers: [],
    },
    Dhcp4Config: null,
    Ip6Config: {
      Addresses: [
        [
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
          },
          128,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        ],
      ],
      AddressData: [
        {
          address: '::1',
          prefix: 128,
        },
      ],
      Gateway: '',
      Routes: [
        [
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
          },
          128,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          256,
        ],
      ],
      RouteData: [
        {
          dest: '::1',
          prefix: 128,
          metric: 256,
        },
      ],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
    },
    Dhcp6Config: null,
    Managed: true,
    Autoconnect: true,
    FirmwareMissing: false,
    NmPluginMissing: false,
    DeviceType: 32,
    AvailableConnections: [
      {
        Unsaved: true,
        Flags: 15,
        Filename: '/run/NetworkManager/system-connections/lo.nmconnection',
      },
    ],
    PhysicalPortId: '',
    Mtu: 65536,
    Metered: 4,
    LldpNeighbors: [],
    Real: true,
    Ip4Connectivity: 3,
    Ip6Connectivity: 3,
    InterfaceFlags: 65539,
    HwAddress: '00:00:00:00:00:00',
    Ports: [],
  },
  {
    Udi: '/sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.1/1-1.1:1.0/net/eth0',
    Path: 'platform-3f980000.usb-usb-0:1.1:1.0',
    Interface: 'eth0',
    IpInterface: 'eth0',
    Driver: 'smsc95xx',
    DriverVersion: '5.10.152-rt75-v7',
    FirmwareVersion: 'smsc95xx USB 2.0 Ethernet',
    Capabilities: 3,
    Ip4Address: 0,
    State: 100,
    StateReason: [100, 0],
    ActiveConnection: {
      Connection: '/org/freedesktop/NetworkManager/Settings/5',
      SpecificObject: '/',
      Id: 'my-static',
      Uuid: '32f7f44b-57bc-4247-8a90-1e34992ed51d',
      Type: '802-3-ethernet',
      Devices: ['/org/freedesktop/NetworkManager/Devices/2'],
      State: 2,
      StateFlags: 92,
      Default: true,
      Ip4Config: '/org/freedesktop/NetworkManager/IP4Config/2',
      Dhcp4Config: '/org/freedesktop/NetworkManager/DHCP4Config/1',
      Default6: false,
      Ip6Config: '/org/freedesktop/NetworkManager/IP6Config/2',
      Dhcp6Config: '/',
      Vpn: false,
      Controller: '/',
      Master: '/',
    },
    Ip4Config: {
      Addresses: [[1186113728, 24, 28485824]],
      AddressData: [
        {
          address: '192.168.178.70',
          prefix: 24,
        },
      ],
      Gateway: '192.168.178.1',
      Routes: [[11708608, 24, 0, 100]],
      RouteData: [
        {
          dest: '192.168.178.0',
          prefix: 24,
          metric: 100,
        },
        {
          dest: '0.0.0.0',
          prefix: 0,
          'next-hop': '192.168.178.1',
          metric: 100,
        },
      ],
      NameserverData: [
        {
          address: '192.168.178.1',
        },
      ],
      Nameservers: [28485824],
      Domains: ['fritz.box'],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 100,
      WinsServerData: [],
      WinsServers: [],
    },
    Dhcp4Config: {
      Options: {
        broadcast_address: '192.168.178.255',
        dhcp_client_identifier: '01:c8:3e:a7:00:17:00',
        dhcp_lease_time: '864000',
        dhcp_server_identifier: '192.168.178.1',
        domain_name: 'fritz.box',
        domain_name_servers: '192.168.178.1',
        expiry: '1698970681',
        interface_mtu: '1500',
        ip_address: '192.168.178.70',
        next_server: '192.168.178.1',
        ntp_servers: '192.168.178.1',
        requested_broadcast_address: '1',
        requested_domain_name: '1',
        requested_domain_name_servers: '1',
        requested_domain_search: '1',
        requested_host_name: '1',
        requested_interface_mtu: '1',
        requested_ms_classless_static_routes: '1',
        requested_nis_domain: '1',
        requested_nis_servers: '1',
        requested_ntp_servers: '1',
        requested_rfc3442_classless_static_routes: '1',
        requested_root_path: '1',
        requested_routers: '1',
        requested_static_routes: '1',
        requested_subnet_mask: '1',
        requested_time_offset: '1',
        requested_wpad: '1',
        routers: '192.168.178.1',
        subnet_mask: '255.255.255.0',
      },
    },
    Ip6Config: {
      Addresses: [
        [
          {
            type: 'Buffer',
            data: [254, 128, 0, 0, 0, 0, 0, 0, 202, 62, 167, 255, 254, 0, 23, 0],
          },
          64,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        ],
        [
          {
            type: 'Buffer',
            data: [32, 1, 10, 97, 96, 166, 219, 1, 209, 168, 90, 159, 152, 105, 99, 143],
          },
          64,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
        ],
      ],
      AddressData: [
        {
          address: 'fe80::ca3e:a7ff:fe00:1700',
          prefix: 64,
        },
        {
          address: '2001:a61:60a6:db01:d1a8:5a9f:9869:638f',
          prefix: 64,
        },
      ],
      Gateway: '',
      Routes: [
        [
          {
            type: 'Buffer',
            data: [32, 1, 10, 97, 96, 166, 219, 1, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          64,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          100,
        ],
        [
          {
            type: 'Buffer',
            data: [254, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          64,
          {
            type: 'Buffer',
            data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
          },
          1024,
        ],
      ],
      RouteData: [
        {
          dest: '2001:a61:60a6:db01::',
          prefix: 64,
          metric: 100,
        },
        {
          dest: 'fe80::',
          prefix: 64,
          metric: 1024,
        },
      ],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 100,
    },
    Dhcp6Config: null,
    Managed: true,
    Autoconnect: true,
    FirmwareMissing: false,
    NmPluginMissing: false,
    DeviceType: 1,
    AvailableConnections: [
      {
        Unsaved: false,
        Flags: 0,
        Filename: '/etc/NetworkManager/system-connections/fallback-link-local-eth0.nmconnection',
      },
      {
        Unsaved: false,
        Flags: 0,
        Filename: '/etc/NetworkManager/system-connections/dhcp-eth0.nmconnection',
      },
      {
        Unsaved: false,
        Flags: 0,
        Filename: '/etc/NetworkManager/system-connections/my-static.nmconnection',
      },
    ],
    PhysicalPortId: '',
    Mtu: 1500,
    Metered: 4,
    LldpNeighbors: [],
    Real: true,
    Ip4Connectivity: 4,
    Ip6Connectivity: 4,
    InterfaceFlags: 65539,
    HwAddress: 'C8:3E:A7:00:17:00',
    Ports: [],
    PermHwAddress: 'C8:3E:A7:00:17:00',
    Speed: 100,
    S390Subchannels: [],
    Carrier: true,
  },
  {
    Udi: '/sys/devices/platform/soc/3f204000.spi/spi_master/spi0/spi0.0/net/pileft',
    Path: 'platform-3f204000.spi-cs-0',
    Interface: 'pileft',
    IpInterface: 'pileft',
    Driver: 'ks8851',
    DriverVersion: '1.00',
    FirmwareVersion: '',
    Capabilities: 3,
    Ip4Address: 0,
    State: 10,
    StateReason: [10, 0],
    ActiveConnection: null,
    Ip4Config: {
      Addresses: [],
      AddressData: [],
      Gateway: '',
      Routes: [],
      RouteData: [],
      NameserverData: [],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
      WinsServerData: [],
      WinsServers: [],
    },
    Dhcp4Config: null,
    Ip6Config: {
      Addresses: [],
      AddressData: [],
      Gateway: '',
      Routes: [],
      RouteData: [],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
    },
    Dhcp6Config: null,
    Managed: false,
    Autoconnect: true,
    FirmwareMissing: false,
    NmPluginMissing: false,
    DeviceType: 1,
    AvailableConnections: [],
    PhysicalPortId: '',
    Mtu: 1500,
    Metered: 0,
    LldpNeighbors: [],
    Real: true,
    Ip4Connectivity: 0,
    Ip6Connectivity: 0,
    InterfaceFlags: 0,
    HwAddress: 'F2:76:D4:26:80:FD',
    Ports: [],
    PermHwAddress: '',
    Speed: 0,
    S390Subchannels: [],
    Carrier: false,
  },
  {
    Udi: '/sys/devices/platform/soc/3f204000.spi/spi_master/spi0/spi0.1/net/piright',
    Path: 'platform-3f204000.spi-cs-1',
    Interface: 'piright',
    IpInterface: 'piright',
    Driver: 'ks8851',
    DriverVersion: '1.00',
    FirmwareVersion: '',
    Capabilities: 3,
    Ip4Address: 0,
    State: 10,
    StateReason: [10, 0],
    ActiveConnection: null,
    Ip4Config: {
      Addresses: [],
      AddressData: [],
      Gateway: '',
      Routes: [],
      RouteData: [],
      NameserverData: [],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
      WinsServerData: [],
      WinsServers: [],
    },
    Dhcp4Config: null,
    Ip6Config: {
      Addresses: [],
      AddressData: [],
      Gateway: '',
      Routes: [],
      RouteData: [],
      Nameservers: [],
      Domains: [],
      Searches: [],
      DnsOptions: [],
      DnsPriority: 0,
    },
    Dhcp6Config: null,
    Managed: false,
    Autoconnect: true,
    FirmwareMissing: false,
    NmPluginMissing: false,
    DeviceType: 1,
    AvailableConnections: [],
    PhysicalPortId: '',
    Mtu: 1500,
    Metered: 0,
    LldpNeighbors: [],
    Real: true,
    Ip4Connectivity: 0,
    Ip6Connectivity: 0,
    InterfaceFlags: 0,
    HwAddress: '3A:61:8E:B3:7C:78',
    Ports: [],
    PermHwAddress: '',
    Speed: 0,
    S390Subchannels: [],
    Carrier: false,
  },
];
